version: '3'
services:

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ./webapp:/var/www/html
    networks:
      - app-network
    depends_on:
        - mysql

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./webapp:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
        - mysql
        - php
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
        - "8080:80"
    restart: always
    networks:
      - app-network
    depends_on:
        - mysql
  
  mysql:
    image: mysql:5.7.37
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql
    networks:
      - app-network

## not template

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge