---
- name: Update apt packages
  apt:
    update_cache: yes
  changed_when: false
  tags:
    - system
  
- include_tasks: installation_tasks.yml
  
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
  
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system