---
- include_tasks: check_containers_present.yml

- name: Restart docker-compose
  docker_compose:
    project_src: "{{ docker_remote_app_dir }}"
    state: absent
  tags:
    - app

- include_tasks: run_containers.yml