---
- include_tasks: check_containers_present.yml

- name: Restart docker-compose
  docker_compose:
    project_src: "{{ docker_remote_app_dir }}"
    restarted: true
    state: present
  tags:
    - app