---
- name: Copy "docker" application folder across
  copy:
    src: "{{ docker_local_app_dir }}"
    dest: "{{ docker_remote_app_dir }}"
  register: copy_app_file
  tags:
    - app

- name: Create docker-compose file
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'env.j2', dest: '{{ docker_remote_app_dir }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ docker_remote_app_dir }}/docker-compose.yaml' }
  tags:
    - app
  when: use_templates

- name: Run docker-compose
  docker_compose:
    project_src: "{{ docker_remote_app_dir }}"
    build: true
    state: present
  tags:
    - app
